apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-delete
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  availability: nova
